###############################################################
##      _          _                 _   _                   ##
##     / \   _ __ (_)_ __ ___   __ _| |_(_) ___  _ __  ___   ##
##    / _ \ | '_ \| | '_ ` _ \ / _` | __| |/ _ \| '_ \/ __|  ##
##   / ___ \| | | | | | | | | | (_| | |_| | (_) | | | \__ \  ##
##  /_/   \_\_| |_|_|_| |_| |_|\__,_|\__|_|\___/|_| |_|___/  ##
##                                                           ##
###############################################################

# ─────────────────────────────────────────────────────────── #
#                     General Animations                      #
# ─────────────────────────────────────────────────────────── #

animations {
    enabled = true
    bezier = easeOutCubic, 0.25, 1, 0.5, 1
    animation = windows, 1, 4, easeOutCubic
    animation = border, 1, 10, easeOutCubic
    animation = fade, 1, 10, easeOutCubic
    animation = workspaces, 1, 6, easeOutCubic
}