#############################################
#### Ollieistic's Hyprland Configuration ####
#############################################

$mainMod = SUPER


##################
#### MONITORS ####
##################

monitor = HDMI-A-1, 1920x1080@60, 1920x0, 1
monitor = DP-2, 1920x1080@60, 0x0, 1


##############################
#### ENVIROMENT VARIABLES ####
##############################

env = HYPRLAND_DEFAULT_LAYOUT=dwindle  
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

env = WLR_NO_HARDWARE_CURSORS=1  
env = WLR_RENDERER=vulkan  
env = __GLX_VENDOR_LIBRARY_NAME=nvidia  
env = __NV_PRIME_RENDER_OFFLOAD=1  
env = VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json  
env = QT_QPA_PLATFORM=wayland  
env = CLUTTER_BACKEND=wayland  
env = MOZ_ENABLE_WAYLAND=1  
  

##################
#### PROGRAMS ####
##################

$terminal = kitty
$fileManager = exec, dolphin
$menu = rofi -show drun -theme ~/.config/rofi/config.rasi

####################
#### AUTO START ####
####################

# Waybar
exec-once = waybar

# Terminal
exec-once = $terminal

# Wallpaper
exec-once = hyprpaper

# Flameshot
exec-once = flameshot &

##################
#### KEYBINDS ####
##################

bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Space, exec,  $menu
bind = $mainMod, K, killactive
bind = $mainMod, F, fullscreen
bind = $mainMod, E, $fileManager
bind = , Print, exec, flameshot gui

bind = $mainMod, X, movewindow, mon:+1
bind = $mainMod, Z, movewindow, mon:-1

bind = $mainMod, U, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = $mainMod, I, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = $mainMod, O, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle

###############
#### INPUT ####
###############

input {
    kb_layout = se
}


####################
#### AESTHETICS ####
####################

general {
    gaps_in = 5
    gaps_out = 15
    border_size = 2
    col.active_border = rgba(FFFFFF88)
    col.inactive_border = rgba(00000088)

    layout = dwindle

    allow_tearing = false
    no_focus_fallback = false

}

decoration {
    rounding = 8

    blur {
	enabled = true
	size = 4
	passes = 2
	new_optimizations = true
	ignore_opacity = false
    }
}

animations {
    enabled = true
    bezier = easeOutCubic, 0.25, 1, 0.5, 1
    animation = windows, 1, 4, easeOutCubic
    animation = border, 1, 10, easeOutCubic
    animation = fade, 1, 10, easeOutCubic
    animation = workspaces, 1, 6, easeOutCubic
}

