#################################
#### Hyprpaper Configuration ####
#################################

# Preload wallpaper(s)
preload = /home/ollieistic/Pictures/wallpapers/pirate-wharf.jpg
preload = /home/ollieistic/Pictures/wallpapers/moon-samurai.jpg

# Primary Monitor's Wallpaper
wallpaper = HDMI-A-1,/home/ollieistic/Pictures/wallpapers/moon-samurai.jpg

# Secondary Monitor's Wallpaper
wallpaper = DP-2,/home/ollieistic/Pictures/wallpapers/pirate-wharf.jpg
