############################################################
##   _   _                                                ##
##  | | | |_   _ _ __  _ __ _ __   __ _ _ __   ___ _ __   ##
##  | |_| | | | | '_ \| '__| '_ \ / _` | '_ \ / _ \ '__|  ##
##  |  _  | |_| | |_) | |  | |_) | (_| | |_) |  __/ |     ##
##  |_| |_|\__, | .__/|_|  | .__/ \__,_| .__/ \___|_|     ##
##        |___/|_|        |_|         |_|                 ##
##                                                        ##
############################################################

# ──────────────────────────────────────────────────────── #
# ──────────────────────────────────────────────────────── #


# ──────────────────────────────────────────────────────── #
#                   Preload Wallpapers                     #
# ──────────────────────────────────────────────────────── #

preload = /home/ollieistic/Pictures/wallpapers/pirate-wharf.jpg
preload = /home/ollieistic/Pictures/wallpapers/moon-samurai.jpg


# ──────────────────────────────────────────────────────── #
#                     Set Wallpapers                       #
# ──────────────────────────────────────────────────────── #

# Primary monitor's wallpaper
wallpaper = HDMI-A-1,/home/ollieistic/Pictures/wallpapers/moon-samurai.jpg

# Secondary monitor's wallpaper
wallpaper = DP-2,/home/ollieistic/Pictures/wallpapers/pirate-wharf.jpg