#############################################
#### Ollieistic's Hyprland Configuration ####
#############################################

$mainMod = SUPER


##################
#### MONITORS ####
##################

monitor = HDMI-A-1, 1920x1080@240, 1920x0, 1.0
monitor = DP-2, 1920x1080@60, 0x0, 1.0

env = HYPRLAND_DEFAULT_LAYOUT=dwindle


##################
#### PROGRAMS ####
##################

$terminal = kitty
$fileManager = exec, dolphin
$menu = XDG_DATA_DIRS=/var/lib/flatpak/exports/share:/usr/local/share:/usr/share GTK_THEME=Adwaita:dark wofi --show drun


####################
#### AUTO START ####
####################

# Terminal
exec-once = $terminal

# Wallpaper
exec-once = hyprpaper

# Flameshot
exec-once = flameshot &


##################
#### KEYBINDS ####
##################

bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Space, exec, $menu
bind = $mainMod, K, killactive
bind = $mainMod, F, fullscreen
bind = $mainMod, E, $fileManager
bind = , Print, exec, flameshot gui


bind = $mainMod, X, movewindow, mon:+1
bind = $mainMod, Z, movewindow, mon:-1

###############
#### INPUT ####
###############

input {
    kb_layout = se
}


####################
#### AESTHETICS ####
####################

general {
    gaps_in = 5
    gaps_out = 15
    border_size = 2
    col.active_border = rgba(33ccffee)
    col.inactive_border = rgba(00000088)

    layout = dwindle

    allow_tearing = false
    no_focus_fallback = false

}

decoration {
    rounding = 8

    blur {
	enabled = true
	size = 4
	passes = 2
	new_optimizations = true
	ignore_opacity = false
    }
}

animations {
    enabled = true
    bezier = easeOutCubic, 0.25, 1, 0.5, 1
    animation = windows, 1, 4, easeOutCubic
    animation = border, 1, 10, easeOutCubic
    animation = fade, 1, 10, easeOutCubic
    animation = workspaces, 1, 6, easeOutCubic
}

