#################################
#### Hyprpaper Configuration ####
#################################

preload = /home/ollieistic/Pictures/wallpapers/tree_1.jpeg
preload = /home/ollieistic/Pictures/wallpapers/moon-samurai.jpg

# Primary Monitor's Wallpaper
wallpaper = HDMI-A-1,/home/ollieistic/Pictures/wallpapers/moon-samurai.jpg

# Secondary Monitor's Wallpaper
wallpaper = DP-2,/home/ollieistic/Pictures/wallpapers/tree_1.jpeg
