#   _                _
#  | |    ___   ___ | | _____
#  | |   / _ \ / _ \| |/ / __|
#  | |__| (_) | (_) |   <\__ \
#  |_____\___/ \___/|_|\_\___/

# -----------------------------
source = ~/.config/hypr/conf/looks/default.conf
