#   __  __             _ _                 
#  |  \/  | ___  _ __ (_) |_ ___  _ __ ___ 
#  | |\/| |/ _ \| '_ \| | __/ _ \| '__/ __|
#  | |  | | (_) | | | | | || (_) | |  \__ \
#  |_|  |_|\___/|_| |_|_|\__\___/|_|  |___/

# ------------------------------------------
# Monitor configuration file for Hyprland
# ------------------------------------------

# Primary Monitor
monitor = HDMI-A-1, 1920x1080@240, 1920x0, 1

# Secondary Monitor
monitor = DP-2, 1920x1080@60, 0x0, 1
