#################################
##   ____        _             ##
##  |  _ \ _   _| | ___  ___   ##
##  | |_) | | | | |/ _ \/ __|  ##
##  |  _ <| |_| | |  __/\__ \  ##
##  |_| \_\\__,_|_|\___||___/  ##
##                             ##
#################################


# ───────────────────────────── #
#         General Rules         #
# ───────────────────────────── #

# Download window (LibreWolf)
windowrulev2 = float, title:^(Enter name of file to save to…)$
windowrulev2 = size 800 600, title:^(Enter name of file to save to…)$
windowrulev2 = center(), title:^(Enter name of file to save to..)$

# Emoji picker (Smile)
windowrulev2 = float, title:^(Smile)
windowrulev2 = size 600 400, title:^(Smile)
windowrulev2 = center(), title:^(Smile)

# Wallpaper front-end (Waypaper)
windowrulev2 = float, title:^(Waypaper)
windowrulev2 = size 850 500, title:^(Waypaper)
windowrulev2 = center(), title:^(Waypaper)

# Picture-in-Picture
windowrulev2 = float, title:^(Picture-in-Picture)
windowrulev2 = size 600 400, title:^(Picture-in-Picture)