####################################################
##  __     __         _       _     _             ##
##  \ \   / /_ _ _ __(_) __ _| |__ | | ___  ___   ##
##   \ \ / / _` | '__| |/ _` | '_ \| |/ _ \/ __|  ##
##    \ V / (_| | |  | | (_| | |_) | |  __/\__ \  ##
##     \_/ \__,_|_|  |_|\__,_|_.__/|_|\___||___/  ##
##                                                ##
####################################################

# ──────────────────────────────────────────────── #
#                General Variables                 #
# ──────────────────────────────────────────────── #

# Main modifier key
$mainMod = SUPER

# Terminal application
$terminal = kitty

# File manager
$fileManager = nautilus

# Wallpaper manager
$wallpaperManager = hyprpaper

# Screenshot manager (mode: save)
$saveScreenshot = hyprshot -m region

# Screenshot manager (mode: copy)
$copyScreenshot = hyprshot -m region --clipboard-only

# Notification manager
$notifManager = dunst

# Notifications listener script
$notifListener = ~/scripts/notifs/notif-listener.sh

# App launcher
$appLauncher = rofi -show drun -theme ~/.config/rofi/config.rasi

# Emoji picker
$emojiPicker = ~/scripts/smile-emojis.sh
