########################################################
##      _             _   _          _   _            ##
##     / \   ___  ___| |_| |__   ___| |_(_) ___ ___   ##
##    / _ \ / _ \/ __| __| '_ \ / _ \ __| |/ __/ __|  ##
##   / ___ \  __/\__ \ |_| | | |  __/ |_| | (__\__\   ##
##  /_/   \_\___||___/\__|_| |_|\___|\__|_|\___|___/  ##
##                                                    ##
########################################################

# ──────────────────────────────────────────────────── #
#                  General Aesthetics                  #
# ──────────────────────────────────────────────────── #
general {
    gaps_in = 5
    gaps_out = 15
    border_size = 2
    col.active_border = rgba(FFFFFF88)
    col.inactive_border = rgba(00000088)

    layout = dwindle

    allow_tearing = false
    no_focus_fallback = false

}


# ──────────────────────────────────────────────────── #
#                More Aesthetics / Looks               #
# ──────────────────────────────────────────────────── #
decoration {
    rounding = 8

    blur {
        enabled = true
        size = 4
        passes = 2
        new_optimizations = true
        ignore_opacity = false
    }
}